### ISSUE TITLE
Add PacketStream Delay circuit

### ISSUE THREAD

**Issue by rowanG077** [clash-lang/clash-protocols#101]
Add a circuit that delays the incoming fragments by `n` fragments and that flushes the remaining fragments on packet end. This can be useful in situations were you want to process a some data but require the results of that data in an earlier part of the packet. Examples of this pattern we encountered implementing the ethernet core:

- Frame check sequence stripping. When validating the frame check sequence you feed it an entire packet, including the frame check sequence. Based on the check we want to set the `abort`. But you want to set the abort on the final fragment before the frame check sequence starts which might no longer be available. Running the Frame check sequence validation over the original stream while forwarding a delayed stream where you can set abort on the correct fragment and also strip of the frame check sequence will solve that.

- IP checksum insertion. The IP checksum is ran over the entire IP header but is not defined at the end of the header. This makes it inconvenient to insert the header as one has to at least buffer a significant portion of the header. Currently IP checksum validation is the critical path for the ethernet core. With the delay circuit in addition to making that less resources heavy we could also pipeline it.

**Comment by t-wallet** [comment]
Implemented in #85.
