### ISSUE TITLE
Motivation for CSignal

### ISSUE THREAD

**Issue by bgamari** [clash-lang/clash-protocols#58]
`Protocols.Internals` provides the following type:
```haskell
-- | Circuit protocol with /CSignal dom a/ in its forward direction, and
-- /CSignal dom ()/ in its backward direction. Convenient for exposing
-- protocol internals.
data CSignal dom a = CSignal (Signal dom a)

instance Default a => Default (CSignal dom a) where
  def = CSignal def

instance Protocol (CSignal dom a) where
  type Fwd (CSignal dom a) = CSignal dom a
  type Bwd (CSignal dom a) = CSignal dom ()
```
It's a bit unclear why this type is necessary. It seems like ideally `Signal` would itself have a `Protocol` instance.

The reason may lie in this comment attached to `CSignal`'s `Protocol` instance:
```haskell
-- XXX: Type families with Signals on LHS are currently broken on Clash:
```

Which suggests that the reason is to work around a compiler deficiency. Discussion with @christiaanb suggested that the issue in question might be https://github.com/clash-lang/clash-compiler/issues/760. However, if this is the case then one would think that the follow, simpler `Protocol` instance would be more appropriate:
```haskell
instance Protocol (CSignal dom a) where
  type Fwd (CSignal dom a) = Signal dom a
  type Bwd (CSignal dom a) = ()
```

So, I suppose my questions are:
 1. Is `CSignal` a temporary workaround for a compiler bug or does it have a more permanent role?
 2. Is there a reason why the simpler `Protocol` instance proposed here wouldn't work?

**Comment by martijnbastiaan** [comment]
I believe this stems from a time where `Fwd` used to be an injective type family. This turned out to be a misguided idea and has been removed [a while back](https://github.com/clash-lang/clash-protocols/pull/31). For `Bwd` I don't quite remember.

> Is `CSignal` a temporary workaround for a compiler bug or does it have a more permanent role?

Temporary workaround.

> Is there a reason why the simpler `Protocol` instance proposed here wouldn't work?

I don't think so, I think we can simplify.

**Comment by martijnbastiaan** [comment]
Three PRs related to this issue (which I believe close it):

* https://github.com/clash-lang/clash-protocols/pull/68
* https://github.com/clash-lang/clash-protocols/pull/67
* https://github.com/clash-lang/clash-protocols/pull/69
